# A general description for this configuration
description = "A test configuration, mostly to exhibit the TOML format"

# The default GLOB pattern to use in limiting files compared
glob = "*"

[commands.sql]
    # Probably any "canonicalizer" will produce OK results.
    executable = "/usr/bin/sqlformat"
    switches = [
        "--reindent_aligned",
        "--identifiers=lower",
        "--strip-comments",
        "--keywords=upper",
    ]    

[commands.ruby]
    # Might choose version not (first) on PATH, e.g.:
    # executable = /usr/local/bin/ruby2.7
    executable = "ruby"
    switches = [ "--dump=parsetree" ]

[commands.python]
    executable = "python"
    switches = [ "-m", "ast", "-a" ]

[commands.javascript]
    # The largish JS code passed in with -e has the additional magic
    # meta-variables ${FILENAME} and ${OPTIONS} that the Golang code will 
    # need to fill in to the JavaScript.  We assume that these same
    # meta-variables will suffice if a different parser than acorn is used.
    executable = "node"
    switches = [
        "-e",
        """\
        'const acorn = require("acorn"); \
         const fs = require("fs"); \
         const source = fs.readFileSync("${FILENAME}", "utf8"); \
         const parse = acorn.parse(source, ${OPTIONS}); \
         console.log(JSON.stringify(parse, null, ""));' \
        """
    ]
    # ecmaVersion: Must be either 3, 5, 6 (or 2015), 7 (2016), 8 (2017), 
    # 9 (2018), 10 (2019), 11 (2020), 12 (2021), 13 (2022), 14 (2023), 
    # or "latest" (the latest the library supports). 
    options = "{sourceType: 'module', ecmaVersion: 'latest'}"

