name: SDT unit tests for JavaScript diffs

on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        node: [ '14', '16', '18' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node packages
        run: npm install acorn

      - name: Node version
        run: node --version

      - name: Test
        run: go test -v pkg/javascript/javascript_test.go
