name: Go package

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        run: python --version

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
        run: ruby --version

      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        run: npm install acorn
        run: node --version

      - name: Test
        run: go test -v ./...
