name: Go package

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test Ruby
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
        run: ruby --version
		run: go test -v pkg/ruby/ruby_test.go

      - name: Test Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
		run: python --version
		run: go test -v pkg/python/python_test.go

      - name: Test JavaScript
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        run: npm install acorn
        run: node --version
        run: go test -v pkg/javascript/javascript_test.go

      - name: Test non-language-specific functionality
        run: go test -v pkg/utils/utils_test.go
